version: '3.8'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ckaew
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
